"""
AI-Powered Resume & Cover Letter Builder
Complete Fixed Version - Production Ready
Author: DOKA CHARLES DANIEL
"""

from __future__ import annotations

import os
import re
from datetime import date
from typing import Optional

import streamlit as st
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt

# -------------------------
# Import utilities with fallbacks
# -------------------------
try:
    from utils.analytics import init_db, log_event, fetch_events
except ImportError:
    import warnings

    warnings.warn("Analytics module not found. Using fallback implementations.")

    def init_db() -> None:
        """Fallback: No-op database initialization"""
        return

    def log_event(event: str, **kwargs) -> None:
        """Fallback: Print events to console"""
        print(f"[EVENT] {event}: {kwargs}")

    def fetch_events():
        """Fallback: Return empty events list"""
        return []


try:
    from utils.branding import (
        apply_page_config,
        render_brand_header,
        render_brand_sidebar,
        render_footer,
        BRAND_LINE,
    )
except ImportError:
    import warnings

    warnings.warn("Branding module not found. Using fallback implementations.")

    def apply_page_config() -> None:
        """Fallback: Basic page configuration"""
        st.set_page_config(
            page_title="AI Resume & Cover Letter Builder",
            page_icon="📝",
            layout="wide",
            initial_sidebar_state="expanded",
        )

    def render_brand_header() -> None:
        """Fallback: Simple header"""
        st.title("📝 AI Resume & Cover Letter Builder")
        st.markdown("*Powered by AI - Created by DOKA CHARLES DANIEL*")

    def render_brand_sidebar() -> None:
        """Fallback: Simple sidebar branding"""
        with st.sidebar:
            st.markdown("### 🚀 Resume Builder AI™")
            st.markdown("*Intelligent Career Tools*")
            st.divider()

    def render_footer() -> None:
        """Fallback: Simple footer"""
        st.markdown("---")
        st.markdown(
            "<div style='text-align: center; color: #666;'>"
            "Resume Builder AI™ - Built by DOKA CHARLES DANIEL<br>"
            "Powered by Streamlit and Hugging Face"
            "</div>",
            unsafe_allow_html=True,
        )

    BRAND_LINE = "Generated by Resume Builder AI™ — by DOKA CHARLES DANIEL"


# -------------------------
# Import models (required)
# -------------------------
try:
    from models.resume_generator_enhanced import ResumeGeneratorEnhanced, CandidateProfile
    from models.cover_letter_enhanced import CoverLetterGeneratorEnhanced, CoverLetterInput
    from app_templates.resume_templates import (
        ResumeTemplateRenderer,
        ResumeData,
        ExperienceItem,
        EducationItem,
    )
except ImportError as e:
    st.error(f"Failed to import required modules: {e}")
    st.error("Please ensure all model/template files are in the correct directories.")
    st.stop()

# -------------------------
# MUST be first Streamlit call
# -------------------------
apply_page_config()

# -------------------------
# App constants
# -------------------------
GENERATED_DIR = "generated_documents"

DEFAULT_RESUME_VALUES = {
    "name": "John Doe",
    "headline": "Senior Software Engineer",
    "years_exp": 5,
    "location": "New York, NY",
    "email": "john.doe@example.com",
    "phone": "+1-555-123-4567",
    "links": "linkedin.com/in/johndoe\ngithub.com/johndoe",
    "core_skills": "Python, JavaScript, React, Node.js, AWS, Docker, Git",
    "tools": "VS Code, Docker, Jenkins, Jira, PostgreSQL",
    "industries": "Technology, SaaS, E-commerce",
    "achievements": (
        "Reduced API response time by 40% through optimization\n"
        "Led team of 5 developers in successful product launch"
    ),
}

SUPPORT_EMAIL = "charlesdanieldoka@gmail.com"
SUPPORT_GITHUB = "https://github.com/Charles-12345/resume_builder_ai_powered"
SUPPORT_DOCS = "https://github.com/Charles-12345/resume_builder_ai_powered#readme"
SUPPORT_ISSUES = "https://github.com/Charles-12345/resume_builder_ai_powered/issues"


# -------------------------
# Utilities
# -------------------------
def ensure_generated_dir() -> None:
    """Create generated documents directory if it doesn't exist."""
    os.makedirs(GENERATED_DIR, exist_ok=True)


def safe_filename(name: str) -> str:
    """Convert a name to a safe filename."""
    name = (name or "").strip().lower()
    name = re.sub(r"[^a-z0-9\-_\s]", "", name)
    name = re.sub(r"\s+", "_", name)
    return name or "document"


def add_brand_footer_to_doc(doc: Document, brand_line: str) -> None:
    """Add a subtle centered footer line to all sections."""
    for section in doc.sections:
        footer = section.footer
        p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()

        # Avoid duplicate lines if re-run
        if p.text.strip() and brand_line not in p.text:
            p = footer.add_paragraph()

        p.text = brand_line
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        if p.runs:
            p.runs[0].font.size = Pt(8)
            p.runs[0].font.italic = True


def build_cover_letter_docx(text: str, out_path: str, include_branding: bool = True) -> None:
    """Build a cover letter DOCX file from text."""
    doc = Document()

    for para in text.split("\n\n"):
        p = para.strip()
        if p:
            doc.add_paragraph(p)

    if include_branding:
        add_brand_footer_to_doc(doc, BRAND_LINE)

    doc.save(out_path)


def get_secret(key: str, default: Optional[str] = None) -> Optional[str]:
    """Safe access to Streamlit Cloud secrets or environment variables."""
    try:
        if hasattr(st, "secrets") and key in st.secrets:
            return str(st.secrets[key])
    except Exception:
        pass
    return os.getenv(key, default)


@st.cache_resource
def get_resume_generator() -> ResumeGeneratorEnhanced:
    return ResumeGeneratorEnhanced()


@st.cache_resource
def get_cover_generator() -> CoverLetterGeneratorEnhanced:
    return CoverLetterGeneratorEnhanced()


def init_session_state() -> None:
    """Initialize session state variables with defaults."""
    defaults = {
        "experience": [],
        "education": [],
        "generated_resume_path": "",
        "generated_cover_path": "",
        "generated_summary": "",
        "generated_cover_letter": "",
        "paid_ok": False,
        "admin_ok": False,
    }
    for key, value in defaults.items():
        st.session_state.setdefault(key, value)


def payment_gate_ui(feature_label: str) -> bool:
    """Display payment gate UI if paywall is enabled."""
    enable_paywall = (get_secret("ENABLE_PAYWALL", "0") == "1")

    if not enable_paywall:
        return True

    if st.session_state.paid_ok:
        return True

    st.warning(f"🔒 {feature_label} is locked. Please unlock to download.")

    pay_link = get_secret("PAYMENT_LINK")
    if pay_link:
        st.link_button("💳 Pay to unlock", pay_link)

    unlock_code_secret = get_secret("UNLOCK_CODE")
    if unlock_code_secret:
        with st.form(f"unlock_form_{feature_label}"):
            code = st.text_input("Enter unlock code", type="password")
            submit = st.form_submit_button("Unlock")
            if submit:
                if code.strip() == unlock_code_secret:
                    st.session_state.paid_ok = True
                    log_event(
                        "payment_confirmed",
                        amount=float(get_secret("PRICE_AMOUNT", "0") or 0),
                        meta=feature_label,
                    )
                    st.success("✅ Unlocked successfully!")
                    st.rerun()
                else:
                    st.error("❌ Invalid unlock code.")
    else:
        st.info("ℹ️ Unlock code not configured. Contact administrator.")

    if st.checkbox("I have paid (temporary unlock)", key=f"paid_tmp_{feature_label}"):
        st.session_state.paid_ok = True

    return bool(st.session_state.paid_ok)


# -------------------------
# Pages
# -------------------------
def page_home() -> None:
    render_brand_sidebar()
    render_brand_header()

    st.markdown(
        """
## Welcome to AI Resume & Cover Letter Builder! 🎉

This tool helps you create professional, ATS-optimized application materials.

### 🚀 What You Can Do
- 📄 Resume Builder (DOCX export)
- ✉️ Cover Letter Generator (DOCX export)
- ✅ ATS Checker (keyword matching + score)
- 📊 Dashboard (analytics)

---
"""
    )

    c1, c2, c3 = st.columns(3)
    with c1:
        st.info("**📝 Easy to Use**\n\nSimple forms with helpful defaults")
    with c2:
        st.success("**🤖 AI-Powered**\n\nSmart content generation")
    with c3:
        st.warning("**⚡ Fast Results**\n\nGenerate docs quickly")

    with st.expander("📧 Contact & Support"):
        st.markdown(
            f"""
- **Email:** {SUPPORT_EMAIL}  
- **GitHub:** {SUPPORT_GITHUB}  
- **Documentation:** {SUPPORT_DOCS}  
- **Issues:** {SUPPORT_ISSUES}
"""
        )


def page_resume_builder() -> None:
    render_brand_sidebar()
    render_brand_header()
    st.subheader("🧱 Resume Builder")

    ensure_generated_dir()
    resume_gen = get_resume_generator()

    col_left, col_right = st.columns([1.2, 1])

    with col_left:
        st.markdown("### 1️⃣ Personal Details")

        full_name = st.text_input("Full name *", value=DEFAULT_RESUME_VALUES["name"])
        headline = st.text_input("Target title / headline role *", value=DEFAULT_RESUME_VALUES["headline"])
        years_exp = st.number_input("Years of experience", 0, 60, DEFAULT_RESUME_VALUES["years_exp"], 1)

        location = st.text_input("Location", value=DEFAULT_RESUME_VALUES["location"])
        email = st.text_input("Email *", value=DEFAULT_RESUME_VALUES["email"])
        phone = st.text_input("Phone", value=DEFAULT_RESUME_VALUES["phone"])

        links_raw = st.text_area("Links (one per line)", value=DEFAULT_RESUME_VALUES["links"], height=80)
        links = [x.strip() for x in links_raw.splitlines() if x.strip()]

        st.divider()
        st.markdown("### 2️⃣ Skills & Tools")

        core_skills_raw = st.text_area("Core skills (comma-separated) *", value=DEFAULT_RESUME_VALUES["core_skills"])
        tools_raw = st.text_area("Tools & Technologies (comma-separated)", value=DEFAULT_RESUME_VALUES["tools"])
        industries_raw = st.text_area("Industries (comma-separated)", value=DEFAULT_RESUME_VALUES["industries"])
        achievements_raw = st.text_area("Top achievements (one per line)", value=DEFAULT_RESUME_VALUES["achievements"], height=100)

        core_skills = [x.strip() for x in core_skills_raw.split(",") if x.strip()]
        tools = [x.strip() for x in tools_raw.split(",") if x.strip()]
        industries = [x.strip() for x in industries_raw.split(",") if x.strip()]
        achievements = [x.strip() for x in achievements_raw.splitlines() if x.strip()]

        st.divider()
        st.markdown("### 3️⃣ Professional Summary")

        job_desc = st.text_area("Optional: Job Description", value="", height=120)
        target_title = st.text_input("Optional: Target title for summary", value=headline)

        if st.button("✨ Generate AI Summary", type="primary", use_container_width=True):
            if not full_name.strip() or not headline.strip():
                st.error("❌ Please provide at least your name and target title.")
            else:
                with st.spinner("🤖 Generating professional summary..."):
                    profile = CandidateProfile(
                        full_name=full_name,
                        title=headline,
                        years_experience=int(years_exp),
                        core_skills=core_skills,
                        industries=industries,
                        achievements=achievements,
                        tools=tools,
                        location=location,
                        email=email,
                        phone=phone,
                        links=links,
                    )
                    result = resume_gen.generate_summary(
                        profile=profile,
                        job_description=job_desc.strip() or None,
                        target_title=target_title.strip() or None,
                    )
                    st.session_state.generated_summary = result.summary
                    log_event("summary_generated", meta=result.source)
                    st.success(f"✅ Summary generated! (Source: {result.source})")

        summary_text = st.text_area("Professional Summary (editable)", value=st.session_state.generated_summary, height=160)

    with col_right:
        st.markdown("### 4️⃣ Experience (Add Multiple)")

        with st.form("experience_form", clear_on_submit=True):
            ex_title = st.text_input("Role title *")
            ex_company = st.text_input("Organization *")
            ex_start = st.text_input("Start date", value="Jan 2023")
            ex_end = st.text_input("End date", value="Present")
            ex_loc = st.text_input("Location (optional)", value="")
            ex_bullets_raw = st.text_area("Bullets (one per line) *", value="Did X\nDid Y", height=120)
            add_ex = st.form_submit_button("➕ Add Experience", use_container_width=True)

        if add_ex:
            if not ex_title.strip() or not ex_company.strip() or not ex_bullets_raw.strip():
                st.error("❌ Provide role title, organization, and at least one bullet.")
            else:
                bullets = [b.strip() for b in ex_bullets_raw.splitlines() if b.strip()]
                st.session_state.experience.append(
                    ExperienceItem(
                        title=ex_title.strip(),
                        company=ex_company.strip(),
                        start_date=ex_start.strip(),
                        end_date=ex_end.strip(),
                        location=ex_loc.strip(),
                        bullets=bullets,
                    )
                )
                st.success("✅ Experience added!")
                st.rerun()

        if st.session_state.experience:
            for i, item in enumerate(st.session_state.experience):
                with st.expander(f"{i+1}. {item.title} @ {item.company}", expanded=False):
                    st.write(f"**Dates:** {item.start_date} – {item.end_date}")
                    if item.location:
                        st.write(f"**Location:** {item.location}")
                    for b in item.bullets:
                        st.write(f"• {b}")
                    if st.button("🗑️ Remove", key=f"rm_ex_{i}"):
                        st.session_state.experience.pop(i)
                        st.rerun()
        else:
            st.info("ℹ️ No experience items yet.")

        st.divider()
        st.markdown("### 5️⃣ Education (Add Multiple)")

        with st.form("education_form", clear_on_submit=True):
            ed_degree = st.text_input("Degree *")
            ed_inst = st.text_input("Institution *")
            ed_year = st.text_input("Year (optional)")
            ed_details = st.text_input("Details (optional)")
            add_ed = st.form_submit_button("➕ Add Education", use_container_width=True)

        if add_ed:
            if not ed_degree.strip() or not ed_inst.strip():
                st.error("❌ Provide degree and institution.")
            else:
                st.session_state.education.append(
                    EducationItem(
                        degree=ed_degree.strip(),
                        institution=ed_inst.strip(),
                        year=ed_year.strip(),
                        details=ed_details.strip(),
                    )
                )
                st.success("✅ Education added!")
                st.rerun()

        if st.session_state.education:
            for i, ed in enumerate(st.session_state.education):
                with st.expander(f"{i+1}. {ed.degree}", expanded=False):
                    st.write(f"**Institution:** {ed.institution}")
                    if ed.year:
                        st.write(f"**Year:** {ed.year}")
                    if ed.details:
                        st.write(f"**Details:** {ed.details}")
                    if st.button("🗑️ Remove", key=f"rm_ed_{i}"):
                        st.session_state.education.pop(i)
                        st.rerun()
        else:
            st.info("ℹ️ No education items yet.")

    st.divider()
    st.markdown("### 6️⃣ Optional Sections")

    col_certs, col_projects = st.columns(2)
    with col_certs:
        certs_raw = st.text_area("Certifications (one per line)", value="", height=90)
    with col_projects:
        projects_raw = st.text_area("Projects (one per line)", value="", height=90)

    certifications = [x.strip() for x in certs_raw.splitlines() if x.strip()]
    projects = [x.strip() for x in projects_raw.splitlines() if x.strip()]

    st.divider()
    st.markdown("### 7️⃣ Export Resume")

    template = st.selectbox("Choose template style", ["modern", "executive", "creative", "technical"], index=0)
    include_branding = st.checkbox("Include branding in footer", value=True)

    brand_line = BRAND_LINE if include_branding else None

    # NOTE: Your ResumeTemplateRenderer must accept brand_line in __init__
    renderer = ResumeTemplateRenderer(output_dir=GENERATED_DIR, brand_line=brand_line)

    export_name = safe_filename(full_name)
    out_filename = f"{export_name}_resume_{template}.docx"

    if st.button("📥 Generate Resume DOCX", type="primary", use_container_width=True):
        if not full_name.strip() or not email.strip():
            st.error("❌ Please provide at least your name and email.")
        else:
            with st.spinner("📄 Generating your resume..."):
                data = ResumeData(
                    full_name=full_name,
                    headline=headline,
                    location=location,
                    email=email,
                    phone=phone,
                    links=links,
                    summary=summary_text.strip(),
                    skills=core_skills,
                    experience=st.session_state.experience,
                    education=st.session_state.education,
                    certifications=certifications,
                    projects=projects,
                )

                if template == "modern":
                    path = renderer.render_modern(data, filename=out_filename)
                elif template == "executive":
                    path = renderer.render_executive(data, filename=out_filename)
                elif template == "creative":
                    path = renderer.render_creative(data, filename=out_filename)
                else:
                    path = renderer.render_technical(data, filename=out_filename)

                st.session_state.generated_resume_path = path
                log_event("resume_generated", template=template)
                st.success(f"✅ Resume generated: `{os.path.basename(path)}`")

    if st.session_state.generated_resume_path and os.path.exists(st.session_state.generated_resume_path):
        st.divider()
        st.markdown("### 📥 Download Your Resume")

        if payment_gate_ui("Resume DOCX download"):
            with open(st.session_state.generated_resume_path, "rb") as f:
                if st.download_button(
                    "⬇️ Download Resume DOCX",
                    data=f.read(),
                    file_name=os.path.basename(st.session_state.generated_resume_path),
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    use_container_width=True,
                ):
                    log_event("resume_downloaded", template=template)
        else:
            st.info("🔒 Complete payment/unlock to download your resume.")


def page_cover_letter() -> None:
    render_brand_sidebar()
    render_brand_header()
    st.subheader("✉️ Cover Letter Generator")

    ensure_generated_dir()
    cover_gen = get_cover_generator()

    col1, col2 = st.columns([1, 1])

    with col1:
        full_name = st.text_input("Full name *", value="John Doe", key="cl_name")
        email = st.text_input("Email", value="john.doe@example.com", key="cl_email")
        phone = st.text_input("Phone", value="+1-555-123-4567", key="cl_phone")
        location = st.text_input("Location", value="New York, NY", key="cl_loc")

        years = st.number_input("Years of experience", 0, 60, 5, 1, key="cl_years")

        company = st.text_input("Company name *", value="Tech Corp", key="cl_company")
        role = st.text_input("Target role *", value="Senior Software Engineer", key="cl_role")
        hiring_manager = st.text_input("Hiring manager name (optional)", value="", key="cl_hm")

        skills_raw = st.text_area("Key skills (comma-separated) *", value="Python, JavaScript, React", key="cl_skills")
        tools_raw = st.text_area("Tools (comma-separated)", value="Git, Jenkins", key="cl_tools")
        achievements_raw = st.text_area("Achievements (one per line) *", value="Did X\nDid Y", key="cl_ach", height=120)
        motivation = st.text_area("Motivation (why this role/company) *", value="I am excited about ...", key="cl_motivation", height=90)
        jd = st.text_area("Job description (optional)", value="", key="cl_jd", height=140)

        tone = st.selectbox("Tone", ["professional", "warm", "confident"], index=0, key="cl_tone")

        if st.button("🪄 Generate Cover Letter", type="primary", use_container_width=True):
            if not full_name.strip() or not company.strip() or not role.strip():
                st.error("❌ Please provide name, company, and role.")
            else:
                with st.spinner("✍️ Generating cover letter..."):
                    data = CoverLetterInput(
                        full_name=full_name.strip(),
                        target_role=role.strip(),
                        company_name=company.strip(),
                        years_experience=int(years),
                        key_skills=[x.strip() for x in skills_raw.split(",") if x.strip()],
                        key_achievements=[x.strip() for x in achievements_raw.splitlines() if x.strip()],
                        tools=[x.strip() for x in tools_raw.split(",") if x.strip()],
                        motivation=motivation.strip(),
                        location=location.strip(),
                        email=email.strip(),
                        phone=phone.strip(),
                        date_line=date.today().strftime("%B %d, %Y"),
                        hiring_manager_name=hiring_manager.strip(),
                    )
                    result = cover_gen.generate_cover_letter(
                        data=data,
                        job_description=jd.strip() or None,
                        tone=tone,
                    )
                    st.session_state.generated_cover_letter = result.cover_letter
                    log_event("cover_letter_generated", meta=result.source)
                    st.success(f"✅ Cover letter generated! (Source: {result.source})")

    with col2:
        include_branding = st.checkbox("Include branding in footer", value=True, key="cl_branding")
        cover_text = st.text_area("Cover letter text (editable)", value=st.session_state.generated_cover_letter, height=520)

        if st.button("📄 Export to DOCX", type="primary", use_container_width=True):
            if not cover_text.strip():
                st.warning("⚠️ No cover letter text to export.")
            else:
                filename = f"{safe_filename(full_name)}_cover_letter.docx"
                out_path = os.path.join(GENERATED_DIR, filename)
                build_cover_letter_docx(cover_text.strip(), out_path, include_branding=include_branding)
                st.session_state.generated_cover_path = out_path
                log_event("cover_letter_exported")
                st.success(f"✅ Cover letter saved: `{filename}`")

        if st.session_state.generated_cover_path and os.path.exists(st.session_state.generated_cover_path):
            st.divider()
            if payment_gate_ui("Cover Letter DOCX download"):
                with open(st.session_state.generated_cover_path, "rb") as f:
                    if st.download_button(
                        "⬇️ Download Cover Letter DOCX",
                        data=f.read(),
                        file_name=os.path.basename(st.session_state.generated_cover_path),
                        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        use_container_width=True,
                    ):
                        log_event("cover_letter_downloaded")
            else:
                st.info("🔒 Complete payment/unlock to download your cover letter.")


def page_ats_checker() -> None:
    render_brand_sidebar()
    render_brand_header()
    st.subheader("✅ ATS Optimization Checker")

    resume_gen = get_resume_generator()

    col1, col2 = st.columns(2)
    with col1:
        resume_text = st.text_area("Paste resume text", height=320)
    with col2:
        jd_text = st.text_area("Paste job description", height=320)

    if st.button("Calculate ATS Score", type="primary", use_container_width=True):
        if not resume_text.strip() or not jd_text.strip():
            st.error("❌ Please provide both resume text and job description.")
            return

        result = resume_gen.ats_optimization_score(resume_text, jd_text)
        log_event("ats_score_calculated")
        st.metric("ATS Optimization Score", f"{result.score}/100")

        st.subheader("Matched keywords (sample)")
        st.write(", ".join(result.matched_keywords) if result.matched_keywords else "None found")

        st.subheader("Missing keywords to consider")
        st.write(", ".join(result.missing_keywords) if result.missing_keywords else "None")

        st.subheader("Notes")
        for n in result.notes:
            st.write(f"- {n}")


def page_dashboard() -> None:
    render_brand_sidebar()
    render_brand_header()
    st.subheader("📊 Admin Dashboard")

    admin_pw = get_secret("ADMIN_PASSWORD")
    if not admin_pw:
        st.warning("ADMIN_PASSWORD is not set.")
        st.info("Set ADMIN_PASSWORD in Streamlit Cloud secrets.")
        return

    if not st.session_state.admin_ok:
        pw = st.text_input("Admin password", type="password")
        if st.button("Unlock dashboard"):
            if pw == admin_pw:
                st.session_state.admin_ok = True
                st.success("Unlocked ✅")
                st.rerun()
            else:
                st.error("Wrong password.")
        return

    rows = fetch_events()
    if not rows:
        st.info("No events yet.")
        return

    try:
        import pandas as pd  # type: ignore

        df = pd.DataFrame(rows, columns=["ts", "event", "template", "amount", "meta"])
        df["ts"] = pd.to_datetime(df["ts"], errors="coerce")

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Resumes Generated", int((df["event"] == "resume_generated").sum()))
        c2.metric("Downloads", int(df["event"].isin(["resume_downloaded", "cover_letter_downloaded"]).sum()))
        c3.metric("Payments Confirmed", int((df["event"] == "payment_confirmed").sum()))
        c4.metric("Revenue", f"${df.loc[df['event']=='payment_confirmed','amount'].fillna(0).sum():.2f}")

        st.subheader("Raw events")
        st.dataframe(df.sort_values("ts", ascending=False), use_container_width=True)

    except Exception:
        st.write(rows)


def page_legal() -> None:
    render_brand_sidebar()
    render_brand_header()
    st.subheader("⚖️ Legal / Trademark Notice")

    st.markdown(
        f"""
**Resume Builder AI™ — by DOKA CHARLES DANIEL**

- The **™** symbol indicates a trademark claim.
- Use **®** only after formal registration.
- Do not upload sensitive personal data you do not need.

### 📧 Contact & Support
- **GitHub:** {SUPPORT_GITHUB}
- **Email:** {SUPPORT_EMAIL}
- **Documentation:** {SUPPORT_DOCS}

**Last Updated:** {date.today().strftime("%B %d, %Y")}
"""
    )


def page_support() -> None:
    render_brand_sidebar()
    render_brand_header()

    st.subheader("📧 Contact & Support")
    st.write("For questions, issues, or feedback:")

    st.markdown(
        f"""
- **Email:** {SUPPORT_EMAIL}  
- **GitHub:** {SUPPORT_GITHUB}  
- **Documentation:** {SUPPORT_DOCS}  
- **Issues:** {SUPPORT_ISSUES}
"""
    )


# -------------------------
# Routing
# -------------------------
def main() -> None:
    init_session_state()
    ensure_generated_dir()
    init_db()

    with st.sidebar:
        st.markdown("### Navigation")
        page = st.radio(
            "Go to",
            ["Home", "Resume Builder", "Cover Letter", "ATS Checker", "Dashboard", "Legal", "Support"],
            index=0,
        )
        st.divider()
        st.markdown("### Quick Stats")
        st.metric("Experience Items", len(st.session_state.experience))
        st.metric("Education Items", len(st.session_state.education))

    page_map = {
        "Home": page_home,
        "Resume Builder": page_resume_builder,
        "Cover Letter": page_cover_letter,
        "ATS Checker": page_ats_checker,
        "Dashboard": page_dashboard,
        "Legal": page_legal,
        "Support": page_support,
    }

    try:
        page_map[page]()
    except Exception as e:
        st.error(f"❌ Page error: {e}")
        st.exception(e)

    render_footer()


if __name__ == "__main__":
    main()
