import streamlit as st

BRAND_LINE = "Generated by Resume Builder AI™ - by DOKA CHARLES DANIEL"

def apply_page_config():
    st.set_page_config(
        page_title="AI Resume & Cover Letter Builder",
        page_icon="📝",
        layout="wide",
        initial_sidebar_state="expanded"
    )

def render_brand_header():
    st.title("📝 AI Resume & Cover Letter Builder")
    st.markdown("*Powered by AI - Created by DOKA CHARLES DANIEL*")

def render_brand_sidebar():
    with st.sidebar:
        st.markdown("### 🚀 Resume Builder AI™")
        st.markdown("*Intelligent Career Tools*")

def render_footer():
    st.markdown("---")
    st.markdown(
        "<div style='text-align: center; color: #666;'>"
        "Resume Builder AI™ - Built with ❤️ by DOKA CHARLES DANIEL<br>"
        "Powered by Streamlit and Hugging Face Transformers"
        "</div>",
        unsafe_allow_html=True
    )
    st.markdown(
        """
        <div style="text-align:center; font-size:12px; color:#666; padding:8px 0;">
          Resume Builder AI™ — by DOKA CHARLES DANIEL • Support: charlesdanieldoka@gmail.com
        </div>
        """,
        unsafe_allow_html=True,
    )
